# Transfer old version pickle to new version pickle in "debug"

In [1]:
# old pickle to new pickle
from utils import save_data, load_data
import pandas as pd
import pickle
pkl1000 = load_data("../analysis/data/backup_data/calcium_pathway_20_shape_5.data.pkl")

In [2]:
pkl1000["debug"]["args"]

{'avg_cnv_per_individual': 5,
 'block_size': 100000,
 'case_dataset': 'delCases',
 'cnv_file': 'data/ISC-r1.CNV.bed',
 'ctrl_dataset': 'delControls',
 'n_case': 10,
 'n_causal_gene': 200,
 'n_ctrl': 10,
 'odds_ratio_params': {'scale': 1, 'shape': 5},
 'output': 'del_sample',
 'prevalence': 0.005,
 'pthwy_gene_file': '../data/calciumgeneset.txt',
 'refgene_file': 'data/refGene.txt.gz'}

In [3]:
pkl1000["debug"]["args"]["n_ctrl"] = 250

In [4]:
pkl1000["debug"]["args"]["n_case"] = 250

In [5]:
pkl1000["debug"]["args"]

{'avg_cnv_per_individual': 5,
 'block_size': 100000,
 'case_dataset': 'delCases',
 'cnv_file': 'data/ISC-r1.CNV.bed',
 'ctrl_dataset': 'delControls',
 'n_case': 250,
 'n_causal_gene': 200,
 'n_ctrl': 250,
 'odds_ratio_params': {'scale': 1, 'shape': 25},
 'output': 'del_sample',
 'prevalence': 0.005,
 'pthwy_gene_file': '../data/calciumgeneset.txt',
 'refgene_file': 'data/refGene.txt.gz'}

In [3]:
pkl1000["debug"]["args"]["refgene_file"] = "../data/refGene.txt.gz"

In [4]:
pkl1000["debug"]["args"]["cnv_file"] = "../data/ISC-r1.CNV.bed"

In [5]:
pkl1000["debug"]["args"]

{'avg_cnv_per_individual': 5,
 'block_size': 100000,
 'case_dataset': 'delCases',
 'cnv_file': '../data/ISC-r1.CNV.bed',
 'ctrl_dataset': 'delControls',
 'n_case': 10,
 'n_causal_gene': 200,
 'n_ctrl': 10,
 'odds_ratio_params': {'scale': 1, 'shape': 5},
 'output': 'del_sample',
 'prevalence': 0.005,
 'pthwy_gene_file': '../data/calciumgeneset.txt',
 'refgene_file': '../data/refGene.txt.gz'}

In [6]:
save_data(pkl1000, "../analysis/data/calcium_pathway_20_shape_5.data.pkl")

In [13]:
pkl1000_n = load_data("../analysis/data/calcium_pathway_1000_shape_25.data.pkl")

In [14]:
pkl1000_n["debug"]["args"]

{'avg_cnv_per_individual': 5,
 'block_size': 100000,
 'case_dataset': 'delCases',
 'cnv_file': '../data/ISC-r1.CNV.bed',
 'ctrl_dataset': 'delControls',
 'n_case': 500,
 'n_causal_gene': 200,
 'n_ctrl': 500,
 'odds_ratio_params': {'scale': 1, 'shape': 25},
 'output': 'del_sample',
 'prevalence': 0.005,
 'pthwy_gene_file': '../data/calciumgeneset.txt',
 'refgene_file': '../data/refGene.txt.gz'}

In [17]:
dat = load_data("../analysis/data/calcium_pathway_20_shape_5.data.blocks.pkl")

In [18]:
dat['data'][0]

    phenotype  FAM102B  FNDC7  HENMT1  PRPF38B
0           1        0      0       0        0
1           1        1      1       1        1
2           1        0      0       0        0
3           1        0      0       0        0
4           1        0      0       0        0
5           1        0      0       0        0
6           1        0      0       0        0
7           1        0      0       0        0
8           1        0      0       0        0
9           1        0      0       0        0
10          0        0      0       0        0
11          0        0      0       0        0
12          0        0      0       0        0
13          0        0      0       0        0
14          0        0      0       0        0
15          0        0      0       0        0
16          0        0      0       0        0
17          0        0      0       0        0
18          0        0      0       0        0
19          0        0      0       0        0

In [19]:
dat['data'][1]

    phenotype  EIF2B3  HECTD3  UROD  ZSWIM5
0           1       0       0     0       0
1           1       0       0     0       0
2           1       1       1     1       1
3           1       0       0     0       0
4           1       0       0     0       0
5           1       0       0     0       0
6           1       0       0     0       0
7           1       0       0     0       0
8           1       0       0     0       0
9           1       0       0     0       0
10          0       0       0     0       0
11          0       0       0     0       0
12          0       0       0     0       0
13          0       0       0     0       0
14          0       0       0     0       0
15          0       0       0     0       0
16          0       0       0     0       0
17          0       0       0     0       0
18          0       0       0     0       0
19          0       0       0     0       0

In [16]:
dat['data'][3]

    phenotype  LOC101927560  LOC101927587  TTLL7
0         1.0           0.0           0.0    0.0
1         1.0           0.0           0.0    0.0
2         1.0           0.0           0.0    0.0
3         1.0           0.0           0.0    0.0
4         1.0           0.0           0.0    0.0
5         1.0           0.0           0.0    0.0
6         1.0           0.0           0.0    0.0
7         1.0           1.0           1.0    1.0
8         1.0           0.0           0.0    0.0
9         1.0           0.0           0.0    0.0
10        0.0           0.0           0.0    0.0
11        0.0           0.0           0.0    0.0
12        0.0           0.0           0.0    0.0
13        0.0           0.0           0.0    0.0
14        0.0           0.0           0.0    0.0
15        0.0           0.0           0.0    0.0
16        0.0           0.0           0.0    0.0
17        0.0           0.0           0.0    0.0
18        0.0           0.0           0.0    0.0
19        0.0           0.0           0.0    0.0