# Implement calcium signaling pathway

Geneset downloaded from KEGG
http://software.broadinstitute.org/gsea/msigdb/cards/KEGG_CALCIUM_SIGNALING_PATHWAY

In [2]:
import pandas as pd
import numpy as np
from pandasql import sqldf
from scipy import stats
from simulation import *

In [3]:
calpath_gene_df = pd.read_table("../data/calciumgeneset.txt", skiprows = 2, header = None, names = ["gene_name"])
# sex chromosome is 23
sw_cnv_df = pd.read_table("../data/swcnv/swcnv.qc6.cnv", sep="\s+")
sw_indiv_df = pd.read_table("../data/swcnv/swcnv.qc6.cnv.indiv", sep="\s+")
sw_cnv_indiv_df = pd.merge(sw_cnv_df, sw_indiv_df, how="inner", on=["FID", "IID"])
sw_cnv_indiv_df["PHE"] = sw_cnv_indiv_df.apply(lambda row: 1 if row["PHE"]==2 else 0, axis=1)
refgene_df = load_reference_gene("data/refGene.txt.gz")

In [4]:
calpath_gene_list = calpath_gene_df["gene_name"].tolist()

In [5]:
print (calpath_gene_list)

['ADCY1', 'ADCY2', 'ADCY3', 'ADCY4', 'ADCY7', 'ADCY8', 'ADCY9', 'ADORA2A', 'ADORA2B', 'ADRA1A', 'ADRA1B', 'ADRA1D', 'ADRB1', 'ADRB2', 'ADRB3', 'AGTR1', 'ATP2A1', 'ATP2A2', 'ATP2A3', 'ATP2B1', 'ATP2B2', 'ATP2B3', 'ATP2B4', 'AVPR1A', 'AVPR1B', 'BDKRB1', 'BDKRB2', 'BST1', 'CACNA1A', 'CACNA1B', 'CACNA1C', 'CACNA1D', 'CACNA1E', 'CACNA1F', 'CACNA1G', 'CACNA1H', 'CACNA1I', 'CACNA1S', 'CALM1', 'CALM2', 'CALM3', 'CALML3', 'CALML5', 'CALML6', 'CAMK2A', 'CAMK2B', 'CAMK2D', 'CAMK2G', 'CAMK4', 'CCKAR', 'CCKBR', 'CD38', 'CHP', 'CHP2', 'CHRM1', 'CHRM2', 'CHRM3', 'CHRM5', 'CHRNA7', 'CYSLTR1', 'CYSLTR2', 'DRD1', 'DRD5', 'EDNRA', 'EDNRB', 'EGFR', 'ERBB2', 'ERBB3', 'ERBB4', 'F2R', 'GNA11', 'GNA14', 'GNA15', 'GNAL', 'GNAQ', 'GNAS', 'GRIN1', 'GRIN2A', 'GRIN2C', 'GRIN2D', 'GRM1', 'GRM5', 'GRPR', 'HRH1', 'HRH2', 'HTR2A', 'HTR2B', 'HTR2C', 'HTR4', 'HTR5A', 'HTR6', 'HTR7', 'ITPKA', 'ITPKB', 'ITPR1', 'ITPR2', 'ITPR3', 'LHCGR', 'LOC729317', 'LTB4R2', 'MYLK', 'MYLK2', 'MYLK3', 'NOS1', 'NOS2', 'NOS3', 'NTSR1', 'OXTR', 'P2RX1', 'P2RX2', 'P2RX3', 'P2RX4', 'P2RX5', 'P2RX6', 'P2RX7', 'PDE1A', 'PDE1B', 'PDE1C', 'PDGFRA', 'PDGFRB', 'PHKA1', 'PHKA2', 'PHKB', 'PHKG1', 'PHKG2', 'PLCB1', 'PLCB2', 'PLCB3', 'PLCB4', 'PLCD1', 'PLCD3', 'PLCD4', 'PLCE1', 'PLCG1', 'PLCG2', 'PLCZ1', 'PLN', 'PPID', 'PPP3CA', 'PPP3CB', 'PPP3CC', 'PPP3R1', 'PPP3R2', 'PRKACA', 'PRKACB', 'PRKACG', 'PRKCA', 'PRKCB', 'PRKCG', 'PRKX', 'PTAFR', 'PTGER1', 'PTGER3', 'PTGFR', 'PTK2B', 'RYR1', 'RYR2', 'RYR3', 'SLC25A31', 'SLC25A4', 'SLC25A5', 'SLC25A6', 'SLC8A1', 'SLC8A2', 'SLC8A3', 'SPHK1', 'SPHK2', 'TACR1', 'TACR2', 'TACR3', 'TBXA2R', 'TNNC1', 'TNNC2', 'TRHR', 'TRPC1', 'VDAC1', 'VDAC2', 'VDAC3']

In [6]:
calpath_gene_pos = pd.merge(refgene_df, calpath_gene_df, how="inner", on=["gene_name"])

In [8]:
query = '''
SELECT gene_name, chrom, min(tx_start), max(tx_end)
FROM calpath_gene_pos
GROUP BY gene_name
'''
calpath_gene_pos = sqldf(query)
calpath_gene_pos = calpath_gene_pos.rename(columns={"min(tx_start)": "gene_start", "max(tx_end)": "gene_end"})

In [7]:
diff = set(calpath_gene_list) - set(calpath_gene_pos["gene_name"].tolist())
print (diff)

{'CHP', 'LOC729317'}

In [11]:
calpath_gene_pos

    gene_name  chrom  gene_start   gene_end
0       ADCY1   chr7    45613738   45762714
1       ADCY2   chr5     7396342    7830194
2       ADCY3   chr2    25042038   25142886
3       ADCY4  chr14    24787554   24804277
4       ADCY7  chr16    50300450   50352045
5       ADCY8   chr8   131792546  132052835
6       ADCY9  chr16     4012649    4166186
7     ADORA2A  chr22    24819564   24838328
8     ADORA2B  chr17    15848230   15879210
9      ADRA1A   chr8    26605666   26724760
10     ADRA1B   chr5   159343739  159400017
11     ADRA1D  chr20     4201277    4229659
12      ADRB1  chr10   115803805  115806667
13      ADRB2   chr5   148206155  148208197
14      ADRB3   chr8    37820513   37824184
15      AGTR1   chr3   148415657  148460790
16     ATP2A1  chr16    28889808   28915830
17     ATP2A2  chr12   110719031  110788897
18     ATP2A3  chr17     3827162    3867758
19     ATP2B1  chr12    89981825   90049844
20     ATP2B2   chr3    10365706   10547374
21     ATP2B3   chrX   152801579  152848387
22     ATP2B4   chr1   203595914  203713209
23     AVPR1A  chr12    63536538   63546590
24     AVPR1B   chr1   206224282  206231482
25     BDKRB1  chr14    96722546   96731100
26     BDKRB2  chr14    96671134   96710666
27       BST1   chr4    15704572   15733796
28    CACNA1A  chr19    13317255   13617274
29    CACNA1B   chr9   140772240  141019076
..        ...    ...         ...        ...
146     PRKCG  chr19    54385437   54410901
147      PRKX   chrX     3522383    3631675
148     PTAFR   chr1    28473676   28520447
149    PTGER1  chr19    14583277   14586174
150    PTGER3   chr1    71318035   71513491
151     PTGFR   chr1    78956727   79006386
152     PTK2B   chr8    27168998   27316908
153      RYR1  chr19    38924339   39078204
154      RYR2   chr1   237205701  237997288
155      RYR3  chr15    33603162   34158304
156  SLC25A31   chr4   128651532  128695454
157   SLC25A4   chr4   186064416  186071538
158   SLC25A5   chrX   118602362  118605359
159   SLC25A6   chrX     1455044    1511039
160    SLC8A1   chr2    40339285   40739575
161    SLC8A2  chr19    47931278   47975307
162    SLC8A3  chr14    70510933   70655787
163     SPHK1  chr17    74380689   74383941
164     SPHK2  chr19    49122547   49133663
165     TACR1   chr2    75273589   75426645
166     TACR2  chr10    71163957   71176674
167     TACR3   chr4   104510624  104640973
168    TBXA2R  chr19     3594503    3606831
169     TNNC1   chr3    52485106   52488057
170     TNNC2  chr20    44451854   44455953
171      TRHR   chr8   110099652  110131812
172     TRPC1   chr3   142443265  142526729
173     VDAC1   chr5   133307565  133340824
174     VDAC2  chr10    76969911   76991207
175     VDAC3   chr8    42249278   42263455

[176 rows x 4 columns]

In [8]:
# https://www.ncbi.nlm.nih.gov/gene/729317
calpath_gene_pos.loc[calpath_gene_pos.shape[0]] = ["LOC729317", "chr2", 65205076, 65206278]
# https://www.ncbi.nlm.nih.gov/gene/?term=CHP
calpath_gene_pos.loc[calpath_gene_pos.shape[0]] = ["CHP", "chr15", 41231149, 41281887]

In [12]:
calpath_gene_pos["chr"] = calpath_gene_pos.apply(lambda row: int(row["chrom"][3:]) 
                                                 if not row["chrom"][3:] in ("X", "Y") else 23, axis=1)

In [10]:
query = '''
SELECT sw.CHR, sw.BP1, sw.BP2, sw.TYPE, sw.PHE, cal.gene_name, cal.gene_start, cal.gene_end, count(sw.FID)
FROM calpath_gene_pos cal LEFT JOIN sw_cnv_indiv_df sw
WHERE sw.CHR == cal.chr
AND (
(sw.BP1 >= cal.gene_start AND sw.BP1 <= cal.gene_end)
OR
(sw.BP2 >= cal.gene_start AND sw.BP2 <= cal.gene_end)
OR
(sw.BP1 <= cal.gene_start AND sw.BP2 >= cal.gene_end)
OR
(sw.BP1 >= cal.gene_start AND sw.BP2 <= cal.gene_end)
)
GROUP BY sw.CHR, sw.BP1, sw.BP2, cal.gene_name, sw.TYPE, sw.PHE
'''
# overlap_CNV_gene_df = sqldf(query).drop_duplicates(subset=("CHR", "BP1", "BP2", "gene_name", "TYPE", "PHE", "count(sw.FID)"))
overlap_CNV_gene_df = sqldf(query)
overlap_CNV_gene_df = overlap_CNV_gene_df.rename(columns={"count(sw.FID)": "n_FID"})

In [11]:
overlap_CNV_gene_df

,CHR,BP1,BP2,TYPE,PHE,gene_name,gene_start,gene_end,n_FID
0,1,1804302,2047584,3,0,CALML6,1846265,1848733,1
1,1,1804302,2047584,3,1,CALML6,1846265,1848733,1
2,1,226748623,226858419,1,1,ITPKB,226819390,226926876,1
3,1,237151125,237493362,1,1,RYR2,237205701,237997288,1
4,1,239678115,239800921,3,0,CHRM3,239792372,240072717,1
5,2,40450245,40614668,1,1,SLC8A1,40339285,40739575,1
6,2,40674308,41559590,3,0,SLC8A1,40339285,40739575,1
7,2,74969763,75323267,3,0,TACR1,75273589,75426645,1
8,2,183023392,183126288,1,1,PDE1A,183004761,183387572,1
9,2,218749319,219480897,3,0,PLCD4,219472487,219501909,1
10,3,4317445,4747247,3,0,ITPR1,4535031,4889524,1
11,3,123486169,123634548,1,0,MYLK,123331142,123603149,1
12,4,9688014,9794193,3,0,DRD5,9783257,9785633,1
13,4,100928014,103125795,1,1,PPP3CA,101944586,102268628,1
14,4,104179046,104766986,1,0,TACR3,104510624,104640973,1
15,5,7532066,9978456,3,1,ADCY2,7396342,7830194,1
16,5,7532066,10040087,3,1,ADCY2,7396342,7830194,1
17,6,118655381,119104706,3,1,PLN,118869425,118882878,1
18,6,118682291,119104706,3,1,PLN,118869425,118882878,1
19,6,118690822,119080379,3,0,PLN,118869425,118882878,1
20,6,118691108,119101336,3,0,PLN,118869425,118882878,1
21,6,118695049,118891582,3,0,PLN,118869425,118882878,1
22,6,118700137,118891582,3,0,PLN,118869425,118882878,1
23,6,118701889,118900024,3,0,PLN,118869425,118882878,2
24,6,118719413,118891582,3,0,PLN,118869425,118882878,1
25,6,118786486,119048269,3,0,PLN,118869425,118882878,1
26,6,118786486,119056733,3,0,PLN,118869425,118882878,1
27,6,118791804,119018502,3,0,PLN,118869425,118882878,1
28,6,118835126,119032859,3,0,PLN,118869425,118882878,1
29,6,118835126,119033109,3,0,PLN,118869425,118882878,1
...,...,...,...,...,...,...,...,...,...
144,22,22997811,24997309,3,1,ADORA2A,24819564,24838328,1
145,22,22997811,25076598,3,1,ADORA2A,24819564,24838328,1
146,22,23689983,24914451,3,1,ADORA2A,24819564,24838328,1
147,22,23689983,25070067,3,1,ADORA2A,24819564,24838328,1
148,22,23692738,25064809,3,1,ADORA2A,24819564,24838328,1
149,22,24447288,25032774,3,1,ADORA2A,24819564,24838328,1
150,23,2703391,3659193,3,1,PRKX,3522383,3631675,1
151,23,2703391,4505504,3,1,PRKX,3522383,3631675,1
152,23,2712661,7044081,1,1,PRKX,3522383,3631675,1
153,23,2741339,3649902,3,1,PRKX,3522383,3631675,3
154,23,2741339,3659193,3,0,PRKX,3522383,3631675,1
155,23,2802568,4859798,3,1,PRKX,3522383,3631675,1
156,23,2811119,7355636,3,1,PRKX,3522383,3631675,1
157,23,2830696,3626408,3,0,PRKX,3522383,3631675,2
158,23,2830696,3649902,3,0,PRKX,3522383,3631675,1
159,23,2830696,3659193,3,0,PRKX,3522383,3631675,2
160,23,2839942,3678164,3,1,PRKX,3522383,3631675,1
161,23,2850801,3637916,3,1,PRKX,3522383,3631675,1
162,23,2850801,3659193,3,0,PRKX,3522383,3631675,2
163,23,2850801,3659193,3,1,PRKX,3522383,3631675,1
164,23,2916735,3539248,3,1,PRKX,3522383,3631675,1
165,23,2916735,3554481,3,0,PRKX,3522383,3631675,1
166,23,2916735,3659193,3,1,PRKX,3522383,3631675,1
167,23,2979529,3539248,3,1,PRKX,3522383,3631675,1
168,23,2979529,3659193,3,0,PRKX,3522383,3631675,1
169,23,2979529,3659193,3,1,PRKX,3522383,3631675,1
170,23,3070182,4736479,3,1,PRKX,3522383,3631675,1
171,23,3231040,3539248,3,0,PRKX,3522383,3631675,1
172,23,3502739,3673759,3,0,PRKX,3522383,3631675,1
173,23,3608067,4120689,3,0,PRKX,3522383,3631675,1

In [12]:
query = '''
SELECT CHR, PHE, TYPE, gene_name, sum(n_FID)
FROM overlap_CNV_gene_df
GROUP BY CHR, PHE, TYPE, gene_start, gene_end
ORDER BY CHR, gene_name
'''
n_occur_CNV_overlap = sqldf(query).drop_duplicates(subset=("CHR", "PHE", "TYPE", "gene_name", "sum(n_FID)"))
n_occur_CNV_overlap = n_occur_CNV_overlap.rename(columns={"sum(n_FID)": "n_FID"})

In [13]:
n_occur_CNV_overlap

    CHR  PHE  TYPE gene_name  n_FID
0     1    0     3    CALML6      1
1     1    1     3    CALML6      1
2     1    0     3     CHRM3      1
3     1    1     1     ITPKB      1
4     1    1     1      RYR2      1
5     2    1     1     PDE1A      1
6     2    0     3     PLCD4      1
7     2    0     3    SLC8A1      1
8     2    1     1    SLC8A1      1
9     2    0     3     TACR1      1
10    3    0     3     ITPR1      1
11    3    0     1      MYLK      1
12    4    0     3      DRD5      1
13    4    1     1    PPP3CA      1
14    4    0     1     TACR3      1
15    5    1     3     ADCY2      2
16    6    0     3       PLN     15
17    6    1     3       PLN      4
18    7    0     3     PDE1C      7
19    7    1     1     PDE1C      1
20    7    1     3     PDE1C      3
21    8    0     3     ADCY8      1
22    9    1     1   CACNA1B      1
23    9    1     3     GNA14      1
24    9    0     3    PPP3R2      1
25   11    1     3     PLCB3      1
26   12    1     1     ITPR2      1
27   12    1     1     P2RX2      1
28   12    1     3     P2RX2      1
29   14    0     3    BDKRB1      3
..  ...  ...   ...       ...    ...
34   15    1     1    CHRNA7      9
35   15    1     3    CHRNA7     20
36   16    0     1    ATP2A1      1
37   16    0     3    ATP2A1      4
38   16    1     1    ATP2A1      5
39   16    1     3    ATP2A1      2
40   16    0     3   CACNA1H      1
41   16    0     3    GRIN2A      1
42   16    0     3     MYLK3      1
43   16    1     3     MYLK3      3
44   16    0     1      PHKB      1
45   17    0     3   ADORA2B      2
46   17    1     3   ADORA2B      1
47   17    0     3    ATP2A3      2
48   17    0     3   CACNA1G      1
49   17    1     3   CACNA1G      1
50   17    0     3     P2RX1      2
51   17    0     3     P2RX5      1
52   17    0     3     PRKCA      1
53   19    1     1    PRKACA      1
54   19    1     3     PRKCG      1
55   20    1     3     NTSR1      1
56   20    0     1     PLCB1      1
57   22    1     3   ADORA2A      6
58   22    0     1     P2RX6      2
59   22    0     3     P2RX6      6
60   22    1     1     P2RX6      8
61   23    0     3      PRKX     13
62   23    1     1      PRKX      1
63   23    1     3      PRKX     15

[64 rows x 5 columns]

In [14]:
# print (n_occur_CNV_overlap["n_FID"][n_occur_CNV_overlap["TYPE"]==3].sum())
overlap_CNV_gene_df["n_FID"].sum()

194

In [15]:
n_occur_CNV_100kb_overlap = sum(overlap_CNV_gene_df[overlap_CNV_gene_df["BP2"]-overlap_CNV_gene_df["BP1"]>100000]["n_FID"])
n_occur_CNV_500kb_overlap = sum(overlap_CNV_gene_df[overlap_CNV_gene_df["BP2"]-overlap_CNV_gene_df["BP1"]>500000]["n_FID"])

In [16]:
print (n_occur_CNV_100kb_overlap, n_occur_CNV_500kb_overlap)

194 80

In [17]:
n_occur_gene_overlap_100kbcnv = len(set(overlap_CNV_gene_df[overlap_CNV_gene_df["BP2"]-overlap_CNV_gene_df["BP1"]>100000]["gene_name"].tolist()))
n_occur_gene_overlap_500kbcnv = len(set(overlap_CNV_gene_df[overlap_CNV_gene_df["BP2"]-overlap_CNV_gene_df["BP1"]>500000]["gene_name"].tolist()))

In [18]:
print (n_occur_gene_overlap_100kbcnv, n_occur_gene_overlap_500kbcnv)

44 18

In [27]:
len(set(overlap_CNV_gene_df[overlap_CNV_gene_df["BP2"]-overlap_CNV_gene_df["BP1"]>100000][overlap_CNV_gene_df["TYPE"]==1]["gene_name"].tolist()))

19